spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: liuyu123456
    url: jdbc:mysql://127.0.0.1:3306/im-core?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: root
  redis:
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000
        min-idle: 10
    password:
  rabbitmq:
    host: localhost
    port: 5672
    addresses: localhost
    username: guest
    password: guest
    #    virtual-host:
    listener:
      simple:
        concurrency: 5
        max-concurrency: 10
        acknowledge-mode: MANUAL
        prefetch: 1
    # publisher-confirms: true
    publisher-returns: true
    template:
      mandatory: true
    cache:
      connection:
        mode: channel
      channel:
        size: 36
        checkout-timeout: 0

  application:
    name: im-core

appConfig:
  privateKey: 123456
  zkAddr: 127.0.0.1:2181
  zkConnectTimeOut: 5000
  imRouteWay: 3 #1 随机 2轮训 3 hash
  consistentHashWay: 1 #如果选用一致性hash的话具体hash算法 1 treemap 2 自定义map
  sendMessageCheckFriend: false # 发送消息是否校验关系链
  sendMessageCheckBlack: false # 发送消息是否校验黑名单
  callbackUrl: http://127.0.0.1:8000/callback
  modifyUserAfterCallback: false # 用户资料变更之后回调开关
  addFriendAfterCallback: false # 添加好友之后回调开关
  addFriendBeforeCallback: false # 添加好友之前回调开关
  modifyFriendAfterCallback: false # 修改好友之后回调开关
  deleteFriendAfterCallback: false # 删除好友之后回调开关
  addFriendShipBlackAfterCallback: false #添加黑名单之后回调开关
  deleteFriendShipBlackAfterCallback: false #删除黑名单之后回调开关
  createGroupAfterCallback: false # 创建群聊之后回调开关
  modifyGroupAfterCallback: false # 修改群聊之后回调开关
  destroyGroupAfterCallback: false # 解散群聊之后回调开关
  deleteGroupMemberAfterCallback: false # 删除群成员之后回调
  addGroupMemberAfterCallback: false # 拉人入群之后回调
  addGroupMemberBeforeCallback: false # 拉人入群之前回调
  sendMessageAfterCallback: false # 发送单聊消息之后
  sendMessageBeforeCallback: false # 发送单聊消息之前
  sendGroupMessageAfterCallback: false # 发送群聊消息之后
  sendGroupMessageBeforeCallback: false # 发送群聊消息之前

# logger 配置
logging:
  config: classpath:logback-spring.xml

server:
  port: 8000


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true
